### ISSUE TITLE
3.14.0 Release TODO

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest#1400]
- [ ] Merge UG 3.13.1 branch into main
- [ ] Update UG hash in makefile
- [ ] Update gdal requirement <3.7

**Comment by phargogh** [comment]
The release was completed!  See https://github.com/natcap/invest/releases/tag/3.14.0
