### ISSUE TITLE
SDR's LS equation does not account for MFD

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#53]
When we refactored SDR to use Multiple Flow Direction, we failed to update SDR's RKLS calculations to account for the fact that aspect (a component of the LS equation) should now account for the possibility that a pixel can flow into 8 possible neighbors.  LS does not currently account for this.

After talking about this with Rich, we decided on the following, corrected approach:

## Given
`FV` = "flow value", the packed 64-bit, 8-direction (4 bits per direction) value coming from MFD Flow Direction
`d` = The integer direction in the form:
```
3 2 1
4 x 0
5 6 7
```
`P_i(d)` = The proportion of flow in pixel `i` in direction `d`
`LS_i'` = A modified `LS` equation that removes the `x_d` term entirely
`x_d` = The length of the pixel from `x` to neighbor `d`.  If `d` is even, this will be `1`,  `sqrt(2)` otherwise.

## Calculate the following
0. Determine the proportional flow `P_i(d) = FV(d) / sum(FV(j) for j in {0..7})`
1. The weighted average of the aspect based on flow value: `FV_avg = sum(1/(x_d) * P_i(d) for d in {0..7})`
2. Calculate `LS_i'`
3. Calculate the modified RKLS: `RKLS_i = R_i * K_i * LS_i' * FV_avg`

## TODOs
- [x] Implement
- [x] Test
- [x] Update the User's Guide
- [x] Ask Rich to look over the updated UG
- [x] Note change in `HISTORY.rst`
- [x] PR this into InVEST

**Comment by phargogh** [comment]
Working on this in my fork at branch `bugfix/update-sdr-ls-for-mfd-33`

**Comment by phargogh** [comment]
Pending #54

**Comment by phargogh** [comment]
Pending #54
