### ISSUE TITLE
Deprecate the Qt UI

### ISSUE THREAD

**Issue by davemfish** [natcap/invest#755]
We're planning on doing this at some point. Here's an issue where we can talk about when & how.

### Criteria that should be met before we do it:
- [x] the Workbench is stable on Windows & Mac
- [x] the Workbench has feature-parity with the Qt UI
- [x] the Workbench is equally accessible to partners and users around the world as Qt.
- [x] Workbench-invest repo management is decided and we are confident in the WB release process
- [x] Post on the forum saying the next release will not include the classic UI. So please try the Workbench and report any issues now.

### todo:
- [x] Replace the invest-autotest script that runs the Qt UI for all models. This could mean doing #1008 . Or it could mean doing #74. Because running all the sampledata through the CLI, plus running the existing Workbench test suite (it builds the UI for all models but does not run them) might be equivalent to actually running all sampledata through the Workbench.
- [x] Remove GUI functionality from the invest CLI. i.e. all `invest run` will be "headless"; remove `invest launch`.
- [x] Replace the Workbench's interim icon with the standard invest logo icon
- [x] Remove `natcap.invest.ui` source
- [x] Remove `requirements-gui.txt`, all references to it
- [x] Remove `natcap.invest.ui` references in `setup.py`
- [x] Remove `ui_tests/ and associated targets in `Makefile`, steps in GHA workflows
- [x] Review `README.rst`
- [x] Remove `installer/` scripts & resources, unless any are still used by the electron build process
- [x] Remove installer build steps from GHA workflows
- [ ] Remove "classic invest" links from our website auto-updater thing

**Comment by davemfish** [comment]
It's been several months since we released the Workbench with `3.11.0`. But we had a bug in usage logging so we won't have usage stats for the workbench until the next release. Sometime after that we can look at the ratio of "workbench" / "classic" invest runs and decide if anyone is really relying on classic invest anymore.

**Comment by davemfish** [comment]
Now that `3.12.0` is released, we'll look at the usage logging stats later this month and then decide when is a good target for deprecation. And then we'll announce an estimated deprecation date that is at least a few more months out.

**Comment by davemfish** [comment]
We looked at usage stats for the `3.12.0` release and found >80% of invest runs for this version were from the workbench. With that many runs, we've only really seen one outstanding Workbench issue on the forum that we don't have a fix for yet (because we don't know the source of the problem). https://community.naturalcapitalproject.org/t/why-does-invest-3-12-stay-in-a-completely-white-state-after-opening-it/3110

**Comment by davemfish** [comment]
> Replace the invest-autotest script that runs the Qt UI for all models. This could mean doing https://github.com/natcap/invest/issues/1008 . Or it could mean doing https://github.com/natcap/invest/issues/74. Because running all the sampledata through the CLI, plus running the existing Workbench test suite (it builds the UI for all models but does not run them) might be equivalent to actually running all sampledata through the Workbench.

We discussed this again and decided it's probably best to do #74 . #1008 Doesn't quite seem necessary for the reason stated here.

**Comment by dcdenu4** [comment]
During our recent chat we decided that the end of January 2023 (Jan. 30th) specifically would be a good time to deprecate Qt UI! We'll try to see if other things line up, like the UNA model or Translations, to include in that release as well.

**Comment by davemfish** [comment]
Done in #1212
