### ISSUE TITLE
Update the release checklist to properly document bugfix releases

### ISSUE THREAD

**Issue by phargogh** [natcap/invest#94]
The [Release Checklist](https://github.com/natcap/invest/wiki/Release-Checklist) is a little out of date now that our release process has been moved to GitHub Actions, and also now that we have automated bugfix releases.  Specific things that need to be covered include:

- [x] What to do if we need to release a bugfix release ahead of the automated schedule
- [x] Update the content of the checklist for GitHub Actions
- [x] How a bugfix release differs in process from a minor release

**Comment by phargogh** [comment]
This was resolved in a recent PR.
